# Generated by Django 3.2.7 on 2021-10-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_newuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_newuser',
            field=models.BooleanField(default=True),
        ),
    ]
