# Generated by Django 3.2.7 on 2021-10-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_newuser_is_newuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='image',
            field=models.ImageField(default='deafault.png', upload_to='profile_pcics'),
        ),
    ]
