# Generated by Django 3.2.7 on 2021-10-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_newuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='image',
            field=models.ImageField(default='user_profiles/deafault.png', upload_to='profile_pcics'),
        ),
    ]
