# Generated by Django 3.2.7 on 2021-10-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_newuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='user_exp',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
