# Generated by Django 3.2.7 on 2021-10-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_newuser_user_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='best_thing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='fav_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='goal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
