# Generated by Django 3.2.7 on 2021-10-16 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codepartner', '0004_userskills_user'),
        ('accounts', '0013_newuser_current_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='user_skills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codepartner.userskills'),
        ),
    ]
