# Generated by Django 3.2.7 on 2021-10-30 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_newuser_user_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='user_skills',
        ),
    ]
