# Generated by Django 3.2.7 on 2021-10-01 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codepartner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
