# Generated by Django 3.2.7 on 2021-10-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codepartner', '0002_delete_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSKills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('python', models.BooleanField(blank=True, default=False)),
                ('javascript', models.BooleanField(blank=True, default=False)),
                ('php', models.BooleanField(blank=True, default=False)),
                ('java', models.BooleanField(blank=True, default=False)),
                ('cpp', models.BooleanField(blank=True, default=False)),
                ('csharp', models.BooleanField(blank=True, default=False)),
                ('ruby', models.BooleanField(blank=True, default=False)),
                ('go', models.BooleanField(blank=True, default=False)),
                ('r', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
