# Generated by Django 3.2.7 on 2021-11-09 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codepartner', '0004_userskills_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('Self-Study', 'Self-Study'), ('Interview Prepration', 'Interview Prepration'), ('Competitive Programming', 'Competitive Programming'), ('Newbie Coding', 'Newbie Coding'), ('Knowledge Sharing', 'Knowledge Sharing'), ('Other', 'Other')], max_length=100)),
                ('language', models.CharField(choices=[('Python', 'Python'), ('Javascript', 'Javascript'), ('C', 'C'), ('C#', 'C#'), ('C++', 'C++'), ('Java', 'Java'), ('PHP', 'PHP'), ('R', 'R'), ('Go', 'Go'), ('Other', 'Other')], max_length=100)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=100)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_book', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
