# Generated by Django 3.2.7 on 2021-11-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codepartner', '0010_alter_discussion_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='created',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
