# Generated by Django 3.2.7 on 2021-11-17 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codepartner', '0013_auto_20211117_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField(default=True)),
                ('comment', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cmntid', to='codepartner.comment')),
                ('user', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cmntuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
